# Generated by script/package-manifests.ts — do not edit by hand.
# Regenerate on every release: the checksums below change each time.
class Wekoya < Formula
  desc "AI pair programming, built and priced for African developers"
  homepage "https://wekoya.tech"
  version "0.1.12"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/Wekoya/wekoya-releases/releases/download/v0.1.12/wekoya-code-darwin-arm64.tar.gz"
      sha256 "1f9637c56b4cc5c874e6f5bb48a2aa3ccf2c873d0c576fc206c05baae6070d7e"
    end
    on_intel do
      url "https://github.com/Wekoya/wekoya-releases/releases/download/v0.1.12/wekoya-code-darwin-x64.tar.gz"
      sha256 "074fd521a3c5662c9e551672804be91c01e740960fa338b30f8bdfb65d6e85a6"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/Wekoya/wekoya-releases/releases/download/v0.1.12/wekoya-code-linux-arm64.tar.gz"
      sha256 "86ff4ff6a4d73ab8cb385eb9968b180c356726d7f856adb0f65301ac16751b51"
    end
    on_intel do
      url "https://github.com/Wekoya/wekoya-releases/releases/download/v0.1.12/wekoya-code-linux-x64.tar.gz"
      sha256 "25c852d0d8205195ffb80f1da829c9bdd8f9a1b3eca1855b0b36c6241dbeaed7"
    end
  end

  def install
    bin.install "wekoya"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/wekoya --version")
  end
end
