# Generated by script/package-manifests.ts — do not edit by hand.
# Regenerate on every release: the checksums below change each time.
class Wekoya < Formula
  desc "AI pair programming, built and priced for African developers"
  homepage "https://wekoya.tech"
  version "0.1.3"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/Wekoya/wekoya-releases/releases/download/v0.1.3/wekoya-code-darwin-arm64.tar.gz"
      sha256 "7bb0ee698844eb94a850c65f7c42c1552cb721cb9a2c17e537934fd7345d4c8a"
    end
    on_intel do
      url "https://github.com/Wekoya/wekoya-releases/releases/download/v0.1.3/wekoya-code-darwin-x64.tar.gz"
      sha256 "d165f5e85ad287f4bbd778eb0eece306a7aabefcdf3d5ba6714c085cd435955c"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/Wekoya/wekoya-releases/releases/download/v0.1.3/wekoya-code-linux-arm64.tar.gz"
      sha256 "bb8dede7b6b6a24f07e7433674cd2b1f773a95dabdc94048d8425ca3c11fc28c"
    end
    on_intel do
      url "https://github.com/Wekoya/wekoya-releases/releases/download/v0.1.3/wekoya-code-linux-x64.tar.gz"
      sha256 "39301f990e509d67722d79483f0bb1935074bd6d62eb29a9dcb39d330b7fdf65"
    end
  end

  def install
    bin.install "wekoya"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/wekoya --version")
  end
end
